### ISSUE TITLE
Blurry images (at least on Safari) due to translate3d

### ISSUE THREAD

**Issue by baba43** [prc5/react-zoom-pan-pinch#248]
Hey, the current mechanism of applying translate3d in combination with scale causes display issues (blurriness) of media like SVGs and Images in some browsers (specifically Safari). After playing around with different workarounds for hours, the only fix that works on my devices is using translateX and translateY instead of translate3d. 

You can investigate this issue yourself, if you want, but anyways I think it would be a good idea to let us override getTransformStyles in any way. Then people that have this issue can also adopt this fix easily. 

Also, if anybody come across this issue, let's talk about it.

**Comment by garrytaulu** [comment]
Or perhaps put in a check to use 2d for Safari and leave 3d for the rest.

**Comment by jlucasoapegro** [comment]
I think it was resolved in https://github.com/prc5/react-zoom-pan-pinch/pull/287

**Comment by Shebuka** [comment]
We updated the component to the latest version and are still having this issue on Safari with regular jpg images

![Screenshot 2023-02-24 at 12 44 01](https://user-images.githubusercontent.com/10927011/221173414-57d72bcd-4223-4fd3-a67f-af3273403ea3.png)
Chrome 110.0.5481.100 (Official Build) (x86_64), Safar 16.2 (17614.3.7.1.7, 17614)
The image is roughly 4k, render size 1k, on the screenshot the scale is 8 (making the resulting zoom close to 1x the original size)

**Comment by Shebuka** [comment]
@prc5 Can you provide the 3 alternatives so I can drop them in and test?

**Comment by prc5** [comment]
1. https://github.com/prc5/react-zoom-pan-pinch/blob/0c311f18a3c7efbde7d20b02c3fbd33b91f8b951/src/utils/styles.utils.ts#L12
2. https://github.com/prc5/react-zoom-pan-pinch/blob/0c311f18a3c7efbde7d20b02c3fbd33b91f8b951/src/utils/styles.utils.ts#L3
3. The same as number 2 but just use translate3d
